CREATE DATABASE IF NOT EXISTS AWS_CONSOLE;
USE AWS_CONSOLE;
CREATE TABLE IF NOT EXISTS two_factor_configs (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 nickname VARCHAR(100) NOT NULL,
 api_key_encrypted TEXT NOT NULL,
 sms_token_encrypted TEXT NULL,
 call_token_encrypted TEXT NULL,
 sms_template_id VARCHAR(100) NULL,
 call_template_id VARCHAR(100) NULL,
 provider VARCHAR(50) NOT NULL DEFAULT '2factor',
 is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id), UNIQUE KEY uq_two_factor_nickname(nickname)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
